name: Wipe All Caches

on:
  workflow_dispatch:

permissions:
  actions: write   # Required to delete caches

jobs:
  wipe:
    runs-on: ubuntu-latest
    steps:
      - name: Wipe GitHub Actions caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'false'